on: [push]
name: CI

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Create env file
          run: |
            mkdir config
            touch config/.env
            echo BEARER_TOKEN=${{ secrets.BEARER_TOKEN }} >> config/.env
            echo CONSUMER_KEY=${{ secrets.CONSUMER_KEY }} >> config/.env
            echo CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }} >> config/.env
            echo ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} >> config/.env
            echo ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> config/.env

        - name: Install Python 3
          uses: actions/setup-python@v1
          with:
            python-version: 3.9

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run unit tests
          run: make test

        - name: Publish Unit Test Results
          uses: EnricoMi/publish-unit-test-result-action@v1.36
          with:
            files: ./results.xml


    lint:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Install Python 3
          uses: actions/setup-python@v1
          with:
            python-version: 3.9

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Lint all src files
          run: make lint

    analyze:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3

          - name: Install Python 3
            uses: actions/setup-python@v1
            with:
              python-version: 3.9

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Perform static analysis on all src files
            run: make analyze

    build:
        needs: [test, lint, analyze]
        runs-on: ubuntu-latest
        steps:

        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: Create env file
          run: |
            mkdir config
            touch config/.env
            echo BEARER_TOKEN=${{ secrets.BEARER_TOKEN }} >> config/.env
            echo CONSUMER_KEY=${{ secrets.CONSUMER_KEY }} >> config/.env
            echo CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }} >> config/.env
            echo ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} >> config/.env
            echo ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> config/.env

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to GitHub container registry
          uses: docker/login-action@v1.10.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ github.token }}

        - name: Lowercase the repo name and username
          run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

        - name: Build and push container image to registry
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
            file: ./Dockerfile          
